export { default as NavBar } from './NavBar/NavBar.jsx'
export { default as Movie } from './Movie/Movie.jsx'
export { default as Home } from './Home/Home.jsx'
export { default as DetailTemp } from './DetailTemp/DetailTemp.jsx'
export { default as DetailCapitulos } from './DetailCapitulos/DetailCapitulos.jsx'
export { default as TheRealMovie } from './TheRealMovie/TheRealMovie.jsx'
export { default as SearchPeliculas } from './SearchPeliculas/SearchPeliculas.jsx'
